// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.jieyou.adhd.domain;

import com.jieyou.adhd.domain.Question;
import com.jieyou.adhd.domain.ScaleDataOnDemand;
import java.util.List;
import java.util.Random;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect QuestionDataOnDemand_Roo_DataOnDemand {
    
    declare @type: QuestionDataOnDemand: @Component;
    
    private Random QuestionDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Question> QuestionDataOnDemand.data;
    
    @Autowired
    private ScaleDataOnDemand QuestionDataOnDemand.scaleDataOnDemand;
    
    public Question QuestionDataOnDemand.getNewTransientQuestion(int index) {
        com.jieyou.adhd.domain.Question obj = new com.jieyou.adhd.domain.Question();
        obj.setScale(scaleDataOnDemand.getRandomScale());
        obj.setSectionDescription("sectionDescription_" + index);
        java.lang.Integer questionNo = new Integer(index);
        if (questionNo < 1) {
            questionNo = 1;
        }
        obj.setQuestionNo(questionNo);
        obj.setQuestionContent("questionContent_" + index);
        return obj;
    }
    
    public Question QuestionDataOnDemand.getSpecificQuestion(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Question obj = data.get(index);
        return Question.findQuestion(obj.getId());
    }
    
    public Question QuestionDataOnDemand.getRandomQuestion() {
        init();
        Question obj = data.get(rnd.nextInt(data.size()));
        return Question.findQuestion(obj.getId());
    }
    
    public boolean QuestionDataOnDemand.modifyQuestion(Question obj) {
        return false;
    }
    
    public void QuestionDataOnDemand.init() {
        data = com.jieyou.adhd.domain.Question.findQuestionEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Question' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<com.jieyou.adhd.domain.Question>();
        for (int i = 0; i < 10; i++) {
            com.jieyou.adhd.domain.Question obj = getNewTransientQuestion(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
